export const DB_SCHEMA_SQL = [
  'PRAGMA foreign_keys = ON;',
  '',
  'CREATE TABLE IF NOT EXISTS Estado (',
  '  EstadoID INTEGER PRIMARY KEY AUTOINCREMENT,',
  '  NombreEstado TEXT NOT NULL UNIQUE',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS Usuario (',
  '  UsuarioID INTEGER PRIMARY KEY AUTOINCREMENT,',
  '  Racha INTEGER NOT NULL,',
  '  Puntaje INTEGER NOT NULL,',
  '  ConfMusica INTEGER NOT NULL,',
  '  ConfSFX INTEGER NOT NULL',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS Modulo (',
  '  ModuloID INTEGER PRIMARY KEY AUTOINCREMENT',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS Quiz (',
  '  QuizID INTEGER PRIMARY KEY AUTOINCREMENT,',
  '  ModuloID INTEGER NOT NULL,',
  '  PuntajeDadoQuiz INTEGER NOT NULL,',
  '',
  '  FOREIGN KEY (ModuloID) REFERENCES Modulo(ModuloID) ON DELETE CASCADE',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS Clase (',
  '  ClaseID INTEGER PRIMARY KEY AUTOINCREMENT,',
  '  ModuloID INTEGER NOT NULL,',
  '  PuntajeDadoClase INTEGER NOT NULL,',
  '',
  '  FOREIGN KEY (ModuloID) REFERENCES Modulo(ModuloID) ON DELETE CASCADE',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS UsuarioModulo (',
  '  UsuarioID INTEGER NOT NULL,',
  '  ModuloID INTEGER NOT NULL,',
  '  EstadoID INTEGER NOT NULL,',
  '',
  '  PRIMARY KEY (UsuarioID, ModuloID),',
  '  FOREIGN KEY (UsuarioID) REFERENCES Usuario(UsuarioID) ON DELETE CASCADE,',
  '  FOREIGN KEY (ModuloID) REFERENCES Modulo(ModuloID) ON DELETE CASCADE,',
  '  FOREIGN KEY (EstadoID) REFERENCES Estado(EstadoID) ON DELETE CASCADE',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS UsuarioClase (',
  '  UsuarioID INTEGER NOT NULL,',
  '  ClaseID INTEGER NOT NULL,',
  '  EstadoID INTEGER NOT NULL,',
  '',
  '  PRIMARY KEY (UsuarioID, ClaseID),',
  '  FOREIGN KEY (UsuarioID) REFERENCES Usuario(UsuarioID) ON DELETE CASCADE,',
  '  FOREIGN KEY (ClaseID) REFERENCES Clase(ClaseID) ON DELETE CASCADE,',
  '  FOREIGN KEY (EstadoID) REFERENCES Estado(EstadoID) ON DELETE CASCADE',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS UsuarioQuiz (',
  '  UsuarioID INTEGER NOT NULL,',
  '  QuizID INTEGER NOT NULL,',
  '  EstadoID INTEGER NOT NULL,',
  '  Resultado INTEGER NOT NULL,',
  '',
  '  PRIMARY KEY (UsuarioID, QuizID),',
  '  FOREIGN KEY (UsuarioID) REFERENCES Usuario(UsuarioID) ON DELETE CASCADE,',
  '  FOREIGN KEY (QuizID) REFERENCES Quiz(QuizID) ON DELETE CASCADE,',
  '  FOREIGN KEY (EstadoID) REFERENCES Estado(EstadoID) ON DELETE CASCADE',
  ');',
].join('\n')

