export const DB_SEED_SQL = [
  "INSERT OR IGNORE INTO Estado (EstadoID, NombreEstado) VALUES (1, 'No Completado');",
  "INSERT OR IGNORE INTO Estado (EstadoID, NombreEstado) VALUES (2, 'Completado');",
  '',
  'INSERT OR IGNORE INTO Modulo (ModuloID) VALUES (1);',
  'INSERT OR IGNORE INTO Modulo (ModuloID) VALUES (2);',
  '',
  'INSERT OR IGNORE INTO Usuario (UsuarioID, Racha, Puntaje, ConfMusica, ConfSFX) VALUES (1, 0, 0, 0, 0);',
  '',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (1, 1, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (2, 1, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (3, 1, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (4, 1, 100);',
  '',
  'INSERT OR IGNORE INTO Quiz (QuizID, ModuloID, PuntajeDadoQuiz) VALUES (1, 1, 500);',
  '',
  'INSERT OR IGNORE INTO UsuarioModulo (UsuarioID, ModuloID, EstadoID) VALUES (1, 1, 1);',
  'INSERT OR IGNORE INTO UsuarioModulo (UsuarioID, ModuloID, EstadoID) VALUES (1, 2, 1);',
  '',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 1, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 2, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 3, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 4, 1);',
  '',
  'INSERT OR IGNORE INTO UsuarioQuiz (UsuarioID, QuizID, EstadoID, Resultado) VALUES (1, 1, 1, 0);',
].join('\n')

