export const DB_SEED_SQL = [
  "INSERT OR IGNORE INTO Estado (EstadoID, NombreEstado) VALUES (1, 'No Completado');",
  "INSERT OR IGNORE INTO Estado (EstadoID, NombreEstado) VALUES (2, 'Completado');",
  '',
  'INSERT OR IGNORE INTO Modulo (ModuloID) VALUES (0);',
  'INSERT OR IGNORE INTO Modulo (ModuloID) VALUES (1);',
  'INSERT OR IGNORE INTO Modulo (ModuloID) VALUES (2);',
  'INSERT OR IGNORE INTO Modulo (ModuloID) VALUES (3);',
  '',
  "INSERT OR IGNORE INTO Usuario (UsuarioID, Racha, Puntaje, ConfMusica, ConfSFX, clave) VALUES (1, 0, 0, 0, 0, 'n/a');",
  '',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (0, 0, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (1, 1, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (2, 1, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (3, 1, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (4, 1, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (5, 2, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (6, 2, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (7, 2, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (8, 2, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (9, 3, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (10, 3, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (11, 3, 100);',
  'INSERT OR IGNORE INTO Clase (ClaseID, ModuloID, PuntajeDadoClase) VALUES (12, 3, 100);',
  '',
  'DELETE FROM UsuarioQuiz WHERE QuizID = 0;',
  'DELETE FROM Quiz WHERE QuizID = 0;',
  'INSERT OR IGNORE INTO Quiz (QuizID, ModuloID, PuntajeDadoQuiz) VALUES (1, 1, 500);',
  'INSERT OR IGNORE INTO Quiz (QuizID, ModuloID, PuntajeDadoQuiz) VALUES (2, 2, 500);',
  'INSERT OR IGNORE INTO Quiz (QuizID, ModuloID, PuntajeDadoQuiz) VALUES (3, 3, 500);',
  '',
  'INSERT OR IGNORE INTO UsuarioModulo (UsuarioID, ModuloID, EstadoID) VALUES (1, 0, 1);',
  'INSERT OR IGNORE INTO UsuarioModulo (UsuarioID, ModuloID, EstadoID) VALUES (1, 1, 1);',
  'INSERT OR IGNORE INTO UsuarioModulo (UsuarioID, ModuloID, EstadoID) VALUES (1, 2, 1);',
  'INSERT OR IGNORE INTO UsuarioModulo (UsuarioID, ModuloID, EstadoID) VALUES (1, 3, 1);',
  '',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 0, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 1, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 2, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 3, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 4, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 5, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 6, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 7, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 8, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 9, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 10, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 11, 1);',
  'INSERT OR IGNORE INTO UsuarioClase (UsuarioID, ClaseID, EstadoID) VALUES (1, 12, 1);',
  '',
  'INSERT OR IGNORE INTO UsuarioQuiz (UsuarioID, QuizID, EstadoID, Resultado) VALUES (1, 1, 1, 0);',
  'INSERT OR IGNORE INTO UsuarioQuiz (UsuarioID, QuizID, EstadoID, Resultado) VALUES (1, 2, 1, 0);',
  'INSERT OR IGNORE INTO UsuarioQuiz (UsuarioID, QuizID, EstadoID, Resultado) VALUES (1, 3, 1, 0);',
].join('\n')

